### ISSUE TITLE
ecommerce for DEDP

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1058]
Tracks tasks for DEDP e-commerce

# ToDos

- [x] enable ecommerce conditionally (DEDP needs it. SCM does not)
- [x] Integration with Cybersource, MIT's preferred ecommerce provider
  - [x] #904 order receipt page / message 
  - [x] #905 order cancellation page
- [x] Fulfillment through edX, by enrolling the user in an audit track
- [x] use personalized prices when checking out
- [x] track the verified status of the user in the micromasters portal

**Comment by pdpinch** [comment]
@noisecapella can you take a look at this and add anything that's missing to the description?

**Comment by pdpinch** [comment]
remove #1043 file storage configuration as we're not taking files anymore.

**Comment by pdpinch** [comment]
@noisecapella now that #913 has been merged, can we check off any of these boxes?

**Comment by noisecapella** [comment]
Just the Cybersource box. We store the result of the payment but we don't do anything with that information yet.

**Comment by pdpinch** [comment]
Can you work on #904?

Are you blocked by mitodl/edx-api-client#26 (I believe Giovanni is working on it)?

**Comment by noisecapella** [comment]
No, once the enrollment API function is in edx-api-client it should be a small change to cause the order fulfillment to actually enroll the user. I'll start on the receipt page. By the way there's been no work done yet to make use of the financial aid calculated price, or to provide different checkout flows for SCM and DEDP

**Comment by Ferdi** [comment]
@noisecapella @pdpinch can you update  the ticket description with all dependent issues ?
