### ISSUE TITLE
MM home page: Improvements

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1111]
Finalize the home page

Todos:
- [x] #1140 copy changes 
- [x] Finalize design/styling
- [x] #1200 fixup metatags per https://github.com/joshbuchea/HEAD
  - [x] Favicons
  - [x] split overloaded `<meta>` tag into two (charset first). See https://github.com/mitodl/micromasters/blob/master/ui/templates/base.html#L4
  - [x] Google+ / Schema.org tags  -- see https://github.com/joshbuchea/HEAD#google--schemaorg
- [x] #1173 Introduce social icons to share
- [x] Finalize imagery  
- [x] Make it responsive
- [x] #1153 Style the mailing list sign up popup
- [x] ~~#1040 add a short description field on the ProgramPage and display it in the home page~~
- [X] #1270 Remove zendesk help button from home page
- [x] #1290 Programs dont always show in the same order

**Comment by pdpinch** [comment]
@annagav @singingwolfboy I added a few more details that need to be addressed in the "SEO" section.

**Comment by pdpinch** [comment]
Regarding favicons, we've already implemented the only size that is approved by MIT. See http://mit.edu/graphicidentity/download-logos.html

**Comment by pdpinch** [comment]
Everything on this this list is done. If we need more home page improvements, new issues should be opened.
