### ISSUE TITLE
MM program pages: Improvements

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1112]
Finalize the program pages

Todos:
- [x] Finalize design/styling
- [x] Faculty profile widget #923 
- [x] #1173 : Introduce social icons to share
- [x] #1134 : Make it SEO friendly (see https://github.com/joshbuchea/HEAD)
- [x] #1189 : Preserve the right side column on FAQ page
- [x] #1179 : "List of courses" widget improvements
- [x] #1190 : FAQ categories
- [x] #1191 : Unique url for each tab
- [x] #1154 : Per-program Google Analytics 
- [x] #1292 / PR #1300 : Faculty thumbnail images on the program page are cropping to the wrong size
- [x] #1237 Truncate the Course Descriptions on the Program page, with a link to Read More on Edx
- [x] #597 Allow CMS user to add (and remove) tabs #597

**Comment by pdpinch** [comment]
Reopening because #1129 only fixed some of the issues here. 

@roberthouse54 can you check off the boxes in the description for anything that's done?

**Comment by roberthouse54** [comment]
I am checking off "Preserve right side column on FAQ page" as this was not the way I designed it. If we want to revisit this, I suggest we do it after the launch.

**Comment by pdpinch** [comment]
@roberthouse54 it seems really odd that the sidebar disappears when the FAQ is opened. Anna or Amir can do this really quickly -- I don't see that it needs more design work.

**Comment by pdpinch** [comment]
Updated 10/10 checked one box and added a few more.
