### ISSUE TITLE
Sign in / up workflow

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1113]
Wrap up sign in/up workflow
- [x]  Remove MM dropdown and related code from the sign up popup (see #1105)
- [x]  #1105 Display program drop-down for users with no program 
- [x] #1182 : Add TOS to sign in/up popup
- [x]  #1231: After creating new profile, user gets a "No Program Enrollment is available" exception

**Comment by roberthouse54** [comment]
As part of this, we will also move the "Terms of Service" w/checkbox from the popup/modal to Sign Up Page 1, since we have the same problem here... The problem with the popup modal in short, is that it contains user inputs that are required for sign up (Selecting a program, and agreeing to ToS), and the user can bypass this modal by clicking LogIn and then returning to the MicroMasters Portal at which point they are in the Sign Up flow.

Mocks are updated on Invision, and pasted below.

![pre_sign_up_dialog 2x](https://cloud.githubusercontent.com/assets/20047260/18836674/0542f122-83cf-11e6-999d-f44b07558165.jpg)

![sign_up_1 2x](https://cloud.githubusercontent.com/assets/20047260/18836681/0930109e-83cf-11e6-868a-e4f40d3177b7.png)

**Comment by pdpinch** [comment]
Thinking about this some more @roberthouse54 : 

the issue we have now is that a user can sign up / log in with edX and only afterwards do they get the terms of service link. That means they've given us their e-mail address and edX profile data before they know our terms of service. 

I think we need to move the terms of service link back into the signup modal and we need to present it to users who "login" and users who "sign up." I know it's not ideal. After 10/15 we can coordinate with edX to get a proper modal log in form from them.
