### ISSUE TITLE
Dashboard:  Course statuses

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1114]
Course statuses update

We currently have 16 status (see screenshot below or [google doc](https://docs.google.com/document/d/1C8JwVxLW0YZBAFwUR06754uz-uyCCEbnvt2TIMJtKk0/edit#heading=h.ho00kfjj2nsd)). They are divided into 4 issues for the front end and two issues for the backend. Since there are some interdependencies, this list is a proposed order for implementation of all the issues:
- [x] #1102 display courses with enrollment open (3 statuses)
- [x] #1078 change "final" grade to depend on `grades` API not `certificates` (backend)
- [x] #1103 / PR #1261 display enrolled courses (with grades) (3 statuses)
- [x] #1023 /  PR #1261 Dashboard: enrollment not open (and after enrollment has ended) (3 statuses)
- [x] #1077 : abstract "MicroMasters" track to include financial aid case (backend)
- [x] #1101 : display passed courses (1 status)
- [x] #939 : Display multiple runs of the same course (6)
- [x] #1021 : Handle verification start and end dates 
## related issues that need to be addressed:
- [x] #1223 / PR #1289 enable 'enroll and pay later'
- [x] #1225 enable 'View on edX' link
- [x] #1242 Possible race condition with order fulfillment 
## can we close these?
- [x] #940 Add tooltip with personal pricing info 
- [x] #833 Allow enrolling a future course run

**Comment by pdpinch** [comment]
I added some more detail to the description and proposed an order for doing the issues.

**Comment by pdpinch** [comment]
@gsidebo I found the missing courses statuses. IMO, we only need the first 5 issues -- #1102, #1078, #1103, #1023 and #1077 for MVP. 

The remaining two are nice to have, but it will be some time before we have enough course runs to use those states.

**Comment by pdpinch** [comment]
Updated description 10/10
