### ISSUE TITLE
Financial aid workflow : UI

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1115]
- [x] #1097 : Cost Calculator Form
- [x] #1044 : Auto-approved requests
- [x] #1098 / PR #1291 : Documents required for verification
- [x] #1302 Change address and phone number for financial aid applications
- [x] #1076 : Allow learners to bypass financial aid & pay full price
- [x] #1100 : Docs reviewed and approved / rejected
- [x] #1308 : Seed currency conversion table on -rc and prod instances 
- [x] #1265 / PR #1310 : Dollar sign for personalized course price in financial aid email message
- [x] #1311 : Use calculated income not original income for determining tier
- [x]  Review page:  Country codes are not expanded

**Comment by pdpinch** [comment]
I updated the description with all the UI stories. I marked #1045 as related, since @alvinsiu has already done it as part of the back-end.

**Comment by pdpinch** [comment]
Updated description on 10/10 by adding a few additional items.
