### ISSUE TITLE
Financial Aid:  Backend/APIs

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#1116]
## Backend/API work to support #1115
- [x] #1044 API endpoint for getting a user's price for a course (part of auto-approved requests)
- [x] #1045 Review Page (not technically back-end)
- [x] #1047 auditing
- [x] #1048 currency conversion
- [x] #1049 review actions 
- [x] #1118 personalize email sent to learners
- [x] #1091 add unique constraint on FinancialAid objects for user and program
- [X] #1041 creating new requests
- [x] #1042 Pending Requests
- [x] #1077 Abstract "MicroMasters" track to include financial aid case
- [x] #1301 / PR #1303 : Move auto-approval income thresholds into database 
- [x] #1267 / PR #1276 : adds error handling for syncing exchange rates with API 
### Not MVP
- #1110 Sending email to learners on status changes.
- #1063 Change FinancialAidSerializer to use a ModelSerializer 
- #1064 Use a permission class to enforce user access for financial aid API

**Comment by pdpinch** [comment]
I updated this with what I think is the current status. I don't think #1110 is necessary for MVP, but let me know if you all disagree. 

@alvinsiu can you review the description as well?

**Comment by alvinsiu** [comment]
I agree - I removed 

> - [ ] #1110 Sending email to learners on status changes

from the MVP section for now.  Sending emails is bundled with #1049, and this one is a discussion for the best place to call the email and function as an implementation optimization, so not MVP.

The only thing I would change is adding #1091 to the MVP because it bundles protection against multiple financial aid requests before the business requirements for that have been defined.  It's also a small issue that won't take much time.

**Comment by alvinsiu** [comment]
All of the MVP components should be merged!
