### ISSUE TITLE
Production Ready

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1220]
## Acceptance Criteria
- [x] Move to production dyno 
- [x] Move db to production db
- [X] #707 Move elasticsearch from bonsai to AWS
- [x] #469 Performance Monitoring
- [x] #980 Production error monitoring
- [x] #1219 Mail Monitoring
- [x] #1218 Load Testing

## out of scope
- We don't think we need to upgrade Redis

**Comment by pdpinch** [comment]
@blarghmatey I think this is everything from my whiteboard. Feel free to add anything else that's missing from the checklist. 

It would be helpful to include some details on the individual issues about how things are configured.
