### ISSUE TITLE
MM home page: Improvements Part 2

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1312]
## for October 15:

- [ ] #1270 Remove ZenDesk button from home page 

## After October 15:

- [ ] #1290 predictable order for program tiles 
- [ ] #1279 CMS: Limit options for child pages #1279

**Comment by pdpinch** [comment]
These were moved to #1111
