### ISSUE TITLE
In person proctored exams

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1796]
We are working on a pilot with Pearson VUE to offer in-person proctored exams for the DEDP micromasters. This integration requires profile data exchange, single-sign on and exam results exchange

### Workflow 

1. When learner enrolls to one of the courses that requires Pearson testing, we send learner’s info to Pearson using a predefined communication protocol. 
2. Once a learner becomes eligible to take the exam with Pearson (pass the course and pay) we send to Pearson the list of exams this learner is authorized to take. 
2. At this point we send an e-mail to the learner to let her know she can schedule the exams with Pearson. Similar message is shown in the dashboard.
3. Learners click “Schedule exam” from within MM dashboard and land into Pearson scheduling site.
4. Learners take the exam.
5. Pearson sends us a file with student grades for that particular exam.
5. Exam grades are shown in the learner’s dashboard.

### Acceptance criteria

- [x] #1800 add additional profile data to profile model
- [x] #1821 request additional profile data from users
  - [x] #2293 add Pearson address fields to Profile API
- [x] #2134 Romanize user's first name and last name
- [x] #1795 Export user profiles for syncing with Pearson
- [x] #1797 Validate the user profiles were accepted by Pearson
- [x] #2076 Send exam authorizations to Pearson
   - ~#2288 Include accommodation info in the exam authorizations~
- [x] #2080 Validate exam authorizations were accepted by Pearson
- [x] #2198 Exam card on dashboard
   - ~~#2232 E-mail Notification of exam eligibility to learners~~ (Pearson will implement)
   - [x] #2407 Exam Status
   - [x] #2408 Single-Sign on with Pearson
   - [x] #2534 list all courses that are eligible
   - [x] #2553 link to (anonymous) web app for finding Pearson exam centers
- [x] #2173 SSO callback urls
- [x] #2558 feature flag / beta feature toggle so we can test in production
- [x] #2427 Production Settings
- ~~#2279 coupons for exam pilot~~
- [x] #2560 suppress payment requirement for pilot exams
- ~~#2542 Retrieve exam scheduled/rescheduled/canceled data~~
- [ ] Reschedule/Cancel an exam button (if possible)
- [x] #2752 Retrieve exam results from Pearson
  - [x] #2790 models 
  - [x] #2791 store exam results
  - [x] #2915 modify dashboard rest API to expose exam grades 
  - [x] #2792 display exam results in dashboard
  - [x] #3084 handle empty fields for no-shows
  - [x] use exam results in determining whether a course is passed
- [x] #2286 restrict learners to 2 exam attempts
- [x] Support retaking exams
- [x] #2895 Exams: keep an audit trail of files we send to Pearson 
- [x] #2896 Exams: keep an audit trail of files we receive from Pearson SFTP
- [x]  #1955 Sign Up: note to clarify that legal name is required
- Updates after pilot
  - [x] #3002 remove FEATURE_EXAMS_CARD_ENABLED feature flag Blocked
  - [x] #3025 update all Pearson profiles
  - [x] #3027 delete all exam authorizations from pilot
  - [x] #3085 add ExamRun model to track when exams occur
 

Deadlines:

- [x] CCD (profile) example files to Pearson by 12/16
- [x] EAD (exam authorization) example files to Pearson by 12/16
- [x] Pearson SSO test environment available by 1/12
- [x] Announce exam dates on 2/20
- [x] Allow profile creation and registration on 3/6
- [x] pilot exams sittings start 3/20
- [x] pilot exams end 4/4
- [x] payment deadline for first paid exams 5/18
- [x] 1st offering of paid exams sittings start 5/22
- [x] 1st offering of paid exams ends 6/4

**Comment by pdpinch** [comment]
@rhysyngsun do we need an additional issue here for tracking the user state?

**Comment by rhysyngsun** [comment]
@pdpinch if we're going to put all of the pearson profile information on a new model (w/ CP-1252 charset enforced) in #1800 rather than add those fields to the existing profile, we can track profile sync status on that model. 

Separately, we do probably want a way to track exam authorization request statuses. I.e. we would have a record for each learner that should be authorized and then track whether we've sent a request or received confirmation.This would be tracked per course run. This can be tracked in the to-be-created tickets for the corresponding items in the checklist above.

**Comment by rhysyngsun** [comment]
@pdpinch Pearson needs an example data file for the exam authorizations by 12/16 so we should get that start sometime this week.

**Comment by rhysyngsun** [comment]
@pdpinch Added an item for "Retrieve exam scheduled/rescheduled/canceled data" so we don't lose sight of that now that we know we can do it.

**Comment by pdpinch** [comment]
I updated this to reflect our shift from using coupons for the pilot to just removing the payment requirement.

**Comment by pdpinch** [comment]
After 10 months, I am closing this epic!

There may be odds and ends, but we've checked all the boxes.
