### ISSUE TITLE
Learners communicate with learners

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#1949]
This epic tracks issues related to "social features" that support learners communicating with other learners. 

- ~~#600 Dashboard: Learners near me component~~
- [x] #2196 Learners should be able to e-mail other learners
- [ ] #2512 Learners search for learners
- [ ] #2888 Enable learner-to-learner email _(added 3/16/17)_
- [ ] #2516 Learners in this program card on dashboard 
- [ ] Learners create study groups
- [ ] Learners can view messaging (e-mail) on portal

### related issues:

- #2564 navigation sidebar

**Comment by gsidebo** [comment]
I mentioned this in the comment on #2196, but it looks like the reference to #943 should be replaced by #2196, and #935 should be moved to the top of the list since it looks like #600 depends on it ([comment link](https://github.com/mitodl/micromasters/issues/600#issuecomment-268314744))

**Comment by pdpinch** [comment]
ok. 

I'm going to delete the comments after this update though, just to keep things clean.
