### ISSUE TITLE
Exams: Trigger exam authorizations when users pass and authorize existing users who already passed

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2077]
Part of #1796 

We need to ensure that the exam authorizations are properly triggered when a user passes a course in edX. We also want users who previously passed a course to get retroactively authorized to take the exam

Criteria for authorizing a user:
- Passed a course in edX.
- Paid for the course.

### Tasks:
- When a user pays for the class, we should: 
  - [ ] Trigger the `ExamProfile` record to be created
  - [ ] Trigger the `ExamAuthorization` record to be created.
- Where we currently determine that the user has passed we should:
  - [ ] Trigger the `ExamAuthorization` record to be created.

### Conditions:
- When we trigger the `ExamProfile` record to be created the following conditions must be met:
  - [ ] Learner must have paid for the course.
  - [ ] `Program.exam_series_code` must be set for the course's program
  - [ ] `Course.exam_module` must be set for the course
- When we trigger the `ExamAuthorization` record to be created the following conditions need to be met:
  - [ ] Learner must have passed the course.
  - [ ] Learner must have paid for the course.
  - [ ] `Program.exam_series_code` must be set for the course's program
  - [ ] `Course.exam_module` must be set for the course

**We won't worry about retroactively authorizing users in this issue**

Open Questions:

- [x] Since it's related to other issues we're working on, is there anything we need to handle special around users passing a course multiple times? At the very least I can ensure we won't have an error if that happens.

**Comment by pdpinch** [comment]
Answer to the open question: the logic to determine whether a use has passed a course should take the max of all the user's enrollments.

**Comment by rhysyngsun** [comment]
@pdpinch I added a requirement for max retakes because I saw that this was on one of the documents:

> Students can only take the same module a maximum of two attempts

**Comment by rhysyngsun** [comment]
Looks like discussion of the eligibility dates happened over here: https://github.com/mitodl/micromasters/issues/2076#issuecomment-266932121

**Comment by pdpinch** [comment]
Since this is blocked and you've picked up some other work, I'm going to move this back to ready. You (or anyone) can pick it up again if it's unblocked.

**Comment by rhysyngsun** [comment]
@pdpinch I've updated the description based on our whiteboarding, could you verify this is correct?

**Comment by amir-qayyum-khan** [comment]
@rhysyngsun 

- So when ever user paid for a course we will authorize him for exam along with exam profile creation.
- When user pass a course we will trigger exam authorize assuming his exam profile is already created.

**Comment by rhysyngsun** [comment]
@amir-qayyum-khan 

- A user should only ever be authorized if they have both paid and passed a courses.
- We should create it regardless. Of there isn't an exam profile that's an error state and we'll check and alert on that when we go to sync the authorization to pearson.

**Comment by pdpinch** [comment]
@rhysyngsun I added the criteria that users have to have paid for a course to be authorized, making the criteria consistent with your 3rd bullet. 

@amir-qayyum-khan 

In all cases, when we create an exam authorization we need to check whether the user meets the criteria: passed and paid.

**Comment by amir-qayyum-khan** [comment]
what about exam profile? is criteria is same for exam profile creation?

**Comment by rhysyngsun** [comment]
@amir-qayyum-khan @pdpinch I just added the criteria of the `exam_series_code` and `exam_module` needing to be set and reorganized the conditions so they're more explicit. Does that make sense now?

**Comment by pdpinch** [comment]
Something to keep in mind: We've been burned a number of times now by not checking all runs of a course when we determine if a user has passed -- not just the most recent one.

**Comment by amir-qayyum-khan** [comment]
@rhysyngsun
> When a user pays for the class, we should:
 [ ] Create an ExamProfile record for them if one does not exist.
 [ ] Trigger the ExamAuthorization record to be created.

this is confusing, when user paid for a course, it is not necessary he passed course, So here we should create ExamAuthorization with pending state, so that ExamProfile

**Comment by rhysyngsun** [comment]
@amir-qayyum-khan both records should get created in the pending state (that's the default for that field so you don't need to specify it). What I'm trying to say here is that because there's not a fixed order of paying and passing it would be cleaner that whenever a user pays or passes that you would call a single task that checks to see if it should create one or both of `ExamProfile` and`ExamAuthorization`.

@pdpinch good point, I think that reinforces what I'm saying about having one task that does all these checks, because then we can just call the task from all the appropriate places.

**Comment by rhysyngsun** [comment]
@pdpinch if you could clarify when exactly we want the profiles synced (at time of payment or time of pass).

**Comment by pdpinch** [comment]
I just confirmed with @Ferdi that profiles should be synced at time of payment, to give us the most possible time to get the profile created successfully at Pearson.
