### ISSUE TITLE
Coupons 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2158]
Design document at https://goo.gl/CMlzHd

We have four near-term use cases for creating coupons for learners:

1. 100% discount coupons for learners who have passed an economics course in the past and will participate in the Pearson exam pilot.
2. 100% discount coupons so members of certain organizations can take all DEDP MicroMasters courses for free.
3. fixed discount for learners who have previously paid for verified certificates
4. Fixed price coupon for affiliated staff.

### Acceptance criteria

- [x] #2192 model for managing coupons
   - type (percentage off; fixed discount)
   - level (program level, course level or (maybe) course-run)
   - for the future, expiration date
- [x] #2222 model to map a user to a coupon
- [x] dashboard: update pricing to reflect coupon 
  - [x] #2322 populate redux store with coupon info API 
  - [x] #2356 calculate prices in frontend 
  - [x] #2355 coupon messaging 
  - [x] #2403 display calculated prices in UI
  - [x] #2335 When price is $0, Pay now should become Enroll now 
  - [x] #2334 hide financial aid options if user has a 100% off coupon for whole program
- [x] #2328 Order Summary page
- [x] #2237 integration with checkout and orders
  - [x] #2321 allow $0 checkouts in checkout API 
  - [x] #2325 redeem coupon in checkout
- [x] method for creating coupons (separate from distributing)
- [x] distribution of  coupons (will be handled by course team)
- [x] #2323 learner interface for applying coupon 
  - [x] #2405 handle anonymous users
- [x] #2400 admin interface for creating coupons
- [x] #2399 fixed price coupons 
- [x] #2195 create audit table to preserve any changes to coupons

**Comment by noisecapella** [comment]
Pseudo-code for redeeming a coupon with models from #2192:

    def redeem_coupon(coupon, user):
        with transaction.atomic():
            if coupon.num_coupons_available == 0:
                raise ValidationError("No coupons left")
            num_redemptions = RedeemedCoupon.objects.filter(order__user=user, coupon=coupon).count()
            if num_redemptions >= coupon.num_redemptions_per_user:
                raise ValidationError("Coupon has no more redemptions left")

            order = create_unfulfilled_order(...)
            RedeemedCoupon.objects.create(order=order, coupon=coupon)
            order.status = 'fulfilled'
            order.save()

**Comment by pdpinch** [comment]
Updated the acceptance criteria to include new issues that George wrote. Also added the two new uses cases, for a total of 4.

**Comment by noisecapella** [comment]
Regarding admin interface, this is in place already, though we may need minor minor changes for functionality since all fields are defaulting to readonly

**Comment by noisecapella** [comment]
Here are some issues that can be worked on in parallel:
- Coupon audit table: #2195. This should be roughly how we've done other audit tables, but we'll need to be careful and add `save_and_log` calls in the right places
 - Attach coupon to user #2323 - this is just a matter of inspecting the query parameters in the dashboard, POSTing to the coupon API to attach the user, and displaying a modal. We do something similar for the order receipt page already.
 - order summary page: #2328 - Just frontend work. @annagav is already working on this
 - coupon messaging: #2355 - this is probably just minor changes here and there in the frontend
 - pay now becomes enroll now: #2335

**Comment by pdpinch** [comment]
@Ferdi @noisecapella I think we're done with this epic. I'm closing it, but if there's anything outstanding, feel free to open it.

**Comment by noisecapella** [comment]
There is this bug which needs to get fixed before we do the $50 off coupons: #2561
