### ISSUE TITLE
Program pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#218]
As an unregistered / not-logged-in user I want to be able to find out more about micromasters programs and possibly enroll. 

Question: How do users enroll in a micromasters program if they haven't registered for a course in the program?

The program page will have 3 tabs:

**Program Home**: https://projects.invisionapp.com/share/AF6XG4X62#/screens/153562858
**FAQ**: https://projects.invisionapp.com/share/AF6XG4X62#/screens/153562856
**Courses**: https://projects.invisionapp.com/share/AF6XG4X62#/screens/153562855 (although the content should look more like http://scm.mit.edu/micromasters/course-descriptions

These pages should all be statically generated, with the variable content coming from markdown files in a separate repository -- allowing course teams to mange the content through github. 
- [ ] ~~Choose a static site generator that can be triggered by github webhooks~~
- [ ] ~~update the micromasters-static repository with the statically generated content~~
- [x] integrate the static site with the micromasters app
- [x] template for Program pages
- [ ] mailchimp sign up (?)
- [X] #1313  google analytics for static pages (?)

**Comment by pdpinch** [comment]
Only one lingering issue in this epic, #679

**Comment by pdpinch** [comment]
I'm not sure if we'll ever tackle #679, but this epic should be closed.
