### ISSUE TITLE
Staff view of learner’s profile page

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2480]
As a staff member, when I am advising a student, I’d like an easy way to look up their enrollments and grades. We will add a card (per program) to the learner profile, only visible to staff. 

### acceptance criteria 

It's recommended to break these into several PRs, so that we can realize some user value without waiting for the whole issue to be addressed. Feel free to open new issues as appropriate. 

Eventually, it will contain:

- [x] number of courses complete
- [x] #2853 Avg program grade
- [x] #2862 Course price
- [x] #2841 Course enrollments (current and past) showing paid vs. auditing status

Also

- [x] Staff and instructor roles are equivalent for this feature
- [x] The staff role must mach the learner's enrollment. For example, Staff on SCM cannot view DEDP learner's data

### related issues
- send message (#943)
- Discussion karma (TBD)

The progress card title should contain the name of the MicroMasters program. If there is no value for any of the data shown, display "- -".

(We have decided to show only one program at a time on this page, because it will be easier to implement within the context of the selected program.)

This closes #2266

![enhanced_profile_faculty_view 2x](https://cloud.githubusercontent.com/assets/20047260/22557015/1f649416-e937-11e6-9e3c-3e54333f3591.jpg)

**Comment by aliceriot** [comment]
As a first thing I want to rename the various components we use for this view, which are all named something like `UserPage`, `User`, `UserPageDialog`, etc to reflect the terminology we actually use (`learner`). It's always a bit of a disconnect to edit the `UserPage` component, which we always talk about as the `LearnerPage`.

**Comment by pdpinch** [comment]
I use "learner" to distinguish between "staff" users and users without that role. ("learner" = "student" but we don't use the s-word for product reasons)

This isn't to say you shouldn't change the components names. I just wanted to clarifyl. 

If a staff member looks at their own learner page, e.g. /learner/pdpinch/ does this change still make sense?

**Comment by aliceriot** [comment]
I think so - the staff users still have access to all the features learners do, so they're not really like a totally separate account type, more like a super learner, if that makes sense? in my mind anyway, haha.

**Comment by aliceriot** [comment]
I think generally we could use that distinction to clarify things that only the staff could see - like the component for this issue could be called `StaffLearnerInfoCard` or something, which would clarify right away a) what it shows info about and 2) who should be able to see it.

**Comment by aliceriot** [comment]
I have a question about this which I think was discussed during planning (but I don't remember the exact outcome).

Should this view be shown only to staff on the currently selected program, or to staff on any program? Meaning, if a learner is enrolled only in `DEDP`, should someone who is staff on `SCM` but not on `DEDP` be able to see this view for that learner?

**Comment by aliceriot** [comment]
Also, should people with the 'instructor' role also see the same view?

**Comment by pdpinch** [comment]
staff view is functionally equivalent to instructor. We have both to mirror how edX is configured, but as of now they both have the same permissions MicroMasters.

**Comment by pdpinch** [comment]
I added acceptance criteria in response to your questions ([here](https://github.com/mitodl/micromasters/issues/2480#issuecomment-278395860) and [here](https://github.com/mitodl/micromasters/issues/2480#issuecomment-278397020))

Let me know if they need further clarificaiton:

> - [ ] Staff and instructor roles are equivalent for this feature
> - [ ] The staff role must mach the learner's enrollment. For example, Staff on SCM cannot view DEDP learner's data

**Comment by aliceriot** [comment]
Cool, thanks!

**Comment by pdpinch** [comment]
@roberthouse54 if we go with one, context-sensitive card, how do we handle the edge case of a learner with multiple enrollments and a user with a staff role on multiple programs? Do we display the program switcher, similar to the dashboard and learners views?

**Comment by aliceriot** [comment]
Displaying the program switcher would be much simpler to implement technically, especially since this is a real edge case I think that's what we should do, but if we don't like that UX we could definitely try to figure out a more complete way to visualize multiple programs at once.

**Comment by pdpinch** [comment]
Is this really easier than just displaying multiple cards?

**Comment by aliceriot** [comment]
I think so, it's just more straightforward because we only have to worry about a single program and don't need any logic around figuring out which programs the learner is enrolled in, which the staff person has access to, etc. All we need to check is that the staff person has staff on the current program.

It's wouldn't be like hugely complicated to display multiple cards or whatever we end up deciding to do, but there's definitely more complication compared with using the program switcher (which is already built).

**Comment by Ferdi** [comment]
@aliceriot what is the "current program" that you are referring too ?    When you view the learner profile, you are outside any program context , no ?

**Comment by aliceriot** [comment]
Well, yes and no. There isn't a UI element to pick the current program (or set the 'focused' program enrollment) but that data is still present in the application's state.

**Comment by Ferdi** [comment]
ok,  although not sure why you guys went with that sort of design. 

Then we just show the card for the current program to users who are staff in that program. And ignore other (edge) cases.

**Comment by aliceriot** [comment]
I just thought about it a little more, at it won't actually be too complicated to show a card for every program in the set `LearnerEnrolledPrograms ∪ StaffPrograms`, based on some code I already wrote.

I just realized we'll need two new API endpoints though, because we don't currently have a way for a user to fetch enrollment info or the dashboard API info for another user.

**Comment by aliceriot** [comment]
so I'm going to take care of that first, I think.

**Comment by Ferdi** [comment]
@aliceriot Just curious, can you get that sort of information from the search index ?

**Comment by aliceriot** [comment]
I think indirectly, we don't store a user's program enrollments in there except implicitly (i.e. by the fact that a user is included in a particular query result set). Not totally sure on that though.

**Comment by aliceriot** [comment]
@pdpinch did we come to a final agreement about what we want to do for this? the work on the staff view for the learner page is somewhat blocked until we have an idea of how to go forward.

one simple thing is that I could do the work to make the dashboard and course enrollments work for other users, and file an issue to come back later and add the elasticsearch querying (which I don't think I'm so qualified to work on, haha).

**Comment by pdpinch** [comment]
Can you outline what changes would be necessary for the dashboard and course enrollments APIs?

**Comment by aliceriot** [comment]
Basically the way they're implemented now assumes that no one besides the currently logged in user would need that info, so the minimal change we could need is to change both of them to take a `username` parameter (or something functionally equivalent) to get information about another user. There would also need to be some permission work to figure out if the user requesting that resources is authorized and so on.

**Comment by aliceriot** [comment]
does that sound like a plan to go forward with for now?

**Comment by pdpinch** [comment]
Yes, as we discussed this afternoon. 

I want to keep an eye on performance though, recognizing that any necessary improvements would probably be behind the API.

**Comment by pdpinch** [comment]
This has been done since July
