### ISSUE TITLE
Automatically send email in the future, as learners meet criteria

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2510]
Staff need to send some emails based on the learner meeting criteria (e.g. having passed two courses, or a new user who employer makes them eligible for a discount). These learners can be identified and messaged via the learner search, but it's extra work and error prone for staff to have to repeatedly check for new learners who meet old criteria. 

Instead, we'll give staff the option to save a query and a message, and have it sent automatically whenever a new learner meets the criteria. 

After discussing options with the team, it seems like using the Percolate function of elastic search is the preferred way to handle this. See this blog post for more information: https://www.elastic.co/blog/when-and-how-to-percolate-1

The UI for this is a simple checkbox in the message pop-up dialog, when it's generated with a search query. 

![future_send_this_email 2x](https://cloud.githubusercontent.com/assets/430126/22658436/0ba24ea8-ec68-11e6-8c2c-b020998b56c0.jpg)

Implementation:
 - [x] Create the model to store percolator queries #2701 
 - [x] On the backend update the mail API to store the value of the query if the checkbox is checked #2704
 - [x] update the redux infrastructure to pass the checkbox value to the REST API #2706
 - [x] add the checkbox in the UI #2707
 - [x] add code/models to match all new user documents and keep track of emails sent #2705

**Comment by pdpinch** [comment]
@noisecapella could you update this ticket with a brief overview of your plan? I see you opened a number of new issues. #2706 in particular I don't quite understand.

**Comment by noisecapella** [comment]
I updated the description

**Comment by noisecapella** [comment]
Do we need to support any kind of templating for the subject and body?

**Comment by noisecapella** [comment]
Also, should we send the email after they complete the profile signup or just when the new user gets created? I'm thinking waiting until after the profile is filled out would give us a better ability to filter users

**Comment by pdpinch** [comment]
I like waiting until the profile is completed. In particular, we want to be able to filter on program. 

Regarding templates, yes, we'd would like to support templating, but I'm not sure exactly how to do this.

**Comment by noisecapella** [comment]
It looks like mailgun supports this in their API: https://documentation.mailgun.com/user_manual.html#batch-sending

I'm going to leave it alone for these issues to keep the scope of what I'm doing narrow, but it shouldn't be hard to add this functionality later

**Comment by pdpinch** [comment]
@noisecapella is this done now that #2707 has been merged?

**Comment by noisecapella** [comment]
Yes
