### ISSUE TITLE
only consider certificates with a status of "downloadable" to be passing certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2538]
It recently come to our attention that it's possible for a user to have an edX certificate that isn't a passing certificate. Up until now, we assumed the presence of any certificate to mean that the user had passed the course. The upshot is that we've displayed a "passed" course status to some users who did not earn a passing grade. 

Fixing this requires a few steps. The first one is a quick fix. 2 + 3 are a more robust fix. 4 is the long-term solution, but requires action from edX

- [x] #2537 modify MMTrack to consider only a certificate status of `downloadable` to be passing
- [x] mitodl/edx-api-client#30 add a `passed` static method to the `Certificate` class of [edx-api-client](https://github.com/mitodl/edx-api-client)
- [ ] #2539 modify MMTrack to use the `passed` flag returned from [edx-api-client](https://github.com/mitodl/edx-api-client)
- [x] persuade edX to added an explicit `passed` flag certificate JSON

**Comment by pdpinch** [comment]
all boxes are checked. I'm closing this.
