### ISSUE TITLE
Allow staff users to create automatic email

### ISSUE THREAD

**Issue by roberthouse54** [mitodl/micromasters#2812]
We want to allow staff users to create a special type of email that will automatically send emails to users when they meet certain criteria. This is a large issue that will be broken down into separate issues. 

When a user clicks "Email these Learners" we will give them two options: a) Send a one-time email, b) Create a Scheduled Email [name is TBD]. 

If the user creates a "Scheduled Email", we will automatically send emails to new users, or to existing users who meet the criteria in the future.

Aspects of this feature:

- Allow users to save emails as templates that can be later selected and used as a template to create new emails.
- Allow users to enter a date range for when to stop and start sending the emails.
- Allow users to enter variables into the email body or subject of the email. For example [user name], [program name], [course name], etc.
- Have a page that lists all "Scheduled Emails", and allows users to manage these emails. That included allowing users to edit current emails, and turn emails on and off.

![scheduled_email 2x](https://cloud.githubusercontent.com/assets/20047260/24111439/c41c0d50-0d6c-11e7-8bfd-da02ccc346a9.jpg)

![manage_automated_emails 2x](https://cloud.githubusercontent.com/assets/20047260/24111530/1bc173e2-0d6d-11e7-8593-fd3614e76147.jpg)

![edit_automated_email 2x](https://cloud.githubusercontent.com/assets/20047260/24111432/be2792b6-0d6c-11e7-9bf8-efa5e6acd638.png)

### MVP acceptance criteria
- [x] #2952 change checkbox (current implementation) to radio buttons (as in mockups)
   - instructional message should appear when `Create an automated email` is chosen
- [x] #2953 display search criteria in recipients 
- [x] #2950 list of existing automated e-mail
   - [x] edit UI 
- [x] #2948/ #2949 / #1938 add WYSIWYG editor to mail composition 

### related issues
- [ ] #2951 save as template / select a template
- [ ] #2954 save and send later / start sending now buttons
- [ ] start / stop sending dates

**Comment by pdpinch** [comment]
Looks like all the boxes are checked on this.
