### ISSUE TITLE
Exams: support 1 authorization per exam series

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#2844]
We need to make an adjustment in how we handle authorizations because exam modules work differently than we expected. Currently, we create 1 authorization record per course, however, Pearson only supports 1 concurrent authorization per exam series with multiple modules specified on that single authorization.

### Subtasks
- [ ] Retrieve exam scheduling results (#2542)
- [ ] Add `ExamModuleAuthorization` record that maps to the course.
  - Should have `ForeignKey` to `ExamAuthorization`
- [ ] Add a `ForeignKey` to `Program` from the current `ExamAuthorization`
  - Migration should populate this with `ExamAuthorization.course.program`
- [ ] Update the EACWriter to write `ExamAuthorization.exam_module_authorizations.course.exam_module` as a comma-delimited string to `ExamModule` column
- [ ] Command to delete existing authorizations that haven't been consumed (this is dependent on #2542 being completed so we know which ones we can delete)
- [ ] Limit learners to 2 exam attempts (#2286)
- [ ] Add a model to track when we're running exams for a series
  - Derive authorization eligibility dates off this

**Comment by pdpinch** [comment]
No longer necessary as Pearson has changed to one exam series per course.
