### ISSUE TITLE
Mail: staff view of AutomaticEmail list

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#2950]
Part of #2812 

Staff need to be able to view and edit any AutomaticEmail they have created. The page will list all automated emails they have created and allows them to manage these emails. This includes allowing them to edit current emails, and turn emails on and off.

### acceptance criteria (MVP)
- [x] new endpoint for listing AutomaticEmail
- [x] #3011 view list of emails. For now, just list the ones created by the current user. Later we may want to allow users to view emails sent by other staff in their program
- [x] simple editing interface, based on the existing mail composition ui (that is to say, it may not have all the features in the design below)
- [x] add link to this page in the sidebar nav, visible to staff only

### out of scope issues
- #2951 Templates 
- Start / end date for sending (needs an issue)
- Removing filters in the mail edit dialog (probably will never do)

![manage_automated_emails 2x](https://cloud.githubusercontent.com/assets/20047260/24111530/1bc173e2-0d6d-11e7-8593-fd3614e76147.jpg)

![edit_automated_email 2x](https://cloud.githubusercontent.com/assets/20047260/24111432/be2792b6-0d6c-11e7-9bf8-efa5e6acd638.png)

**Comment by rhysyngsun** [comment]
@pdpinch I see these features and not being immediately implementable without changing the data model:

- Templates
- Start / end date for sending

I would also see editing the recipient filters as being nontrivial to do without leveraging SearchKit somehow since that's currently how we generate the query filters in the first place.

So that leaves us at being able to change the subject line and body and enabled/disabled as features we could immediately implement, is that sufficient functionality for an MVP here?

**Comment by pdpinch** [comment]
Sure thing. I was hinting at that in the description, and I've tried to make it more explicit now. I'd like to have the edit UI use the same component that Amir is working on now in #2952 and #2953, which does not include templates, start/end date, or editing of filters.

**Comment by aliceriot** [comment]
have we already decided what the url for viewing the list of created emails should be?

if not I'll probably just go with `/automaticemails` or `/emails` or something along those lines.

**Comment by pdpinch** [comment]
No discussion so far. I think `/automaticemails` would be best for now. We may want to have more email views later.

**Comment by aliceriot** [comment]
cool, will do

**Comment by aliceriot** [comment]
also! we're going to put a link in the nav sidebar to this page - what should the title of that link be? 'Automatic Emails', 'Email Campaigns', etc?

**Comment by aliceriot** [comment]
also @roberthouse54 do you have a material design icon you think would be good for that link? 

[this one](https://material.io/icons/#ic_email) seems like a good candidate to me!

**Comment by roberthouse54** [comment]
Yes, looks good. Thanks!

**Comment by roberthouse54** [comment]
Well, I am not sure on the link title. I originally had "Scheduled Emails". Tobias suggested "Email Campaigns", although I think Ferdi does not like that, and it perhaps has a connotation of marketing campaigns. I think we should either go with "Automated Emails" or "Email Campaigns" but I am ambivalent about which of those we choose. @pdpinch @Ferdi ?

**Comment by aliceriot** [comment]
I just closed #3011, so we now have an index page and a link in the sidebar. You can currently only toggle the 'enabled' state, on Monday I'll get going on adding editing functionality.

**Comment by aliceriot** [comment]
I think this is ready to close - we now have the index page and an 'edit' link that lets you do some basic editing. @roberthouse54 what do you think?

**Comment by roberthouse54** [comment]
I think we can close it, as long as it meets the acceptance criteria, which it seems to. Can you post a screenshot of it?

**Comment by aliceriot** [comment]
sure:

![automatic_emails](https://cloud.githubusercontent.com/assets/6207644/24966989/8f441354-1f76-11e7-8f14-aae91ce0dba3.png)
