### ISSUE TITLE
Exams: add ExamRun model to track when exams occur

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/micromasters#3085]
Adding this model should solve a few problems:

- We currently re-create `ExamAuthorization`s ad infinitum even if there are not actually any exams scheduled. This makes deleting the pilot period ones for #3027 difficult/impossible.
- We scope `ExamSeriesCode` to program/course currently. That structure needs to change for #3077 anyway and these values could, in theory, be scoped only to a single `ExamRun` so we should just put in on this record to make our lives easier anyway.
- This causes us to have to do odd things like set `FEATURE_EXAMS_CARD_VISIBLE=False` to hide the card when there aren't any exams to take (this should obviate the need for this flag entirely so we could then do #3002)
- We "unique" the authorizations on user + course + a rough bound of eligibility dates. If we added a foreign key to this new table we could do away with that in favor of a real unique constraint.

So I propose we do the following (each phase represent a deployment so as to avoid errors in prod):

### ~~Phase 1 - #3112~~
- [x] Add `ExamRun` model with these fields: `date_first_eligible`, `date_last_eligible`, `exam_series_code`
- [x] Admin page for `ExamRun`
- [x] Add nullable foreign key to `ExamRun` from `ExamAuthorization`
- [x] Make `date_first_eligible` and `date_last_eligible` on `ExamAuthorization` nullable
- [x] Update [this code](https://github.com/mitodl/micromasters/blob/master/exams/utils.py#L106-L126) to `get_or_create` on `user` + `course` + `exam_run` and only for the first `ExamRun` in the future for that course.

### ~~Phase 2 - #3122~~

- [x] Create a dummy `ExamRun` record for each course that was in the pilot and assign the pilot authorizations to these. We should give them an `ExamSeriesCode` of `"PILOT"` or similar so they're clearly marked. (Addresses #3027)
- [x] Change `ExamAuthorization.exam_run` to be non-nullable
- [x] Update the `ExamAuthorization` writer to use the fields from `ExamRun`

### ~~Phase 3 - #3123~~
- [x] Remove these fields from `ExamAuthorization`:  `date_first_eligible`, `date_last_eligible`
- [x] Remove these fields from `Course`:  `exam_module`
- [x] Remove these fields from `Program`:  `exam_series_code`

**Comment by rhysyngsun** [comment]
@pdpinch previously when we created the `ExamAuthorization` records we displayed the exam button if `date_first_eligible <= now() <= date_last_eligible`, so my question is practically how do you you think that approach will change? Will we in practice set the `date_first_eligible` to the first day a learner can start scheduling or do we need another `DateTime` field for that?

I'm planning on having both these eligibility dates be a full `DateTimeField` rather than `DateField` which would give us control over precisely what hour/minute the button showed up. We truncate the time from the data when we send the authorization which is why we didn't use this previously
