### ISSUE TITLE
Change "Field of Study" to a select drop-down in education degree detail view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#333]
As an admin, I'd like to have users use a controlled vocabulary for fields of study, normalizing this field and making it easier to do (faceted) searches. 

As a user, I'd like to be able to start typing my field of study and have the ui present me with a list of matches, so I don't have to guess what fields of study are recognized. 

We will use the [Classification of Instructional Programs (CIP)](https://nces.ed.gov/ipeds/cipcode/resources.aspx?y=55) vocabulary from the National Center on Education Statistics

We will store the vocabulary in the database, and build an API to query it. This avoids transferring the whole 2000+ programs to the client. (this is a different approach than what we do currently for country and territory data).

This story includes:

- [ ] #442 model for fields of study (ON HOLD)
- [ ] #442 REST API (ON HOLD)
- [x] #443 updating the react component to use a static JSON file of the data

**Comment by pdpinch** [comment]
We're now looking at adapting this controlled vocabulary: http://digitalcommons.bepress.com/cgi/viewcontent.cgi?article=1008&context=reference

**Comment by pdpinch** [comment]
@Ferdi the digitalcommons document lead me to the [National Academies site](http://sites.nationalacademies.org/PGA/Resdoc/PGA_044521).

Their list has about 80 fields of study, compared with digitalcommons' list of 1300. 

How about if I merge the MIT list (113) with the National Academies list?

**Comment by Ferdi** [comment]
I think more is better, no?  What's your concern ?

**Comment by pdpinch** [comment]
Browser performance, and user confusion. But I could be overreacting.  

If we go with the digitalcommons list, would you use the full hierachy, or just the leaf? For example, "Arts and Humanities: Classics: Ancient History, Greek and Roman through Late Antiquity" or just "Ancient History, Greek and Roman through Late Antiquity"

There's also a few MIT departments that don't exist in the digitalcommons list. Can I just add those? (e.g. "Brain and Cognitive Science")

**Comment by Ferdi** [comment]
I'm not sure , none of these seems consistent. What linkedin version looks like , can you guess ?

**Comment by pdpinch** [comment]
After some more discussion, Ferdi and I have decided to go with the Classification of Instructional Programs (CIP) vocabulary, managed by the National Center on Education Statistics. You can browse the 2010 (most recent) and download a csv from their [resource page](https://nces.ed.gov/ipeds/cipcode/resources.aspx?y=55).

Besides being comprehensive, and a well-recognized standard, we also like this vocabulary because it has a hierarchy to it, which we think will help with (faceted) searching and reporting in the future. We should be sure that the implementation maintains that hierarchy somehow so, for example, we can retrieve a list of all the students with degrees in "biological and biomedical sciences" 

It is a long list, and after some discussion with @giocalitri and @noisecapella we think this needs a (small) API so that we can query only for the values the user is interested in. For example, when the user fills out the profile form for their bachelors degree, they could start typing HIS. The resulting query would return fields of study including "History" and "Cell/Cellular Biology and Histology." These fields would be used to populate a drop-down list.

**Comment by giocalitri** [comment]
I briefly looked into a basic fulltext search using Postgres and it does not look as easy as I thought.
https://dlo.me/archives/2014/09/01/postgresql-fts/

We might want to consider using elasticsearch.

**Comment by pdpinch** [comment]
Closing this for now. If we want to revisit it in the future, we can open a new issue.
