### ISSUE TITLE
Forums MVP: Peter creates channel for DEDP and SCM users

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3467]
As a staff member of a program, I want to create a channel based off a profile search query. All the learners who match the query should be subscribed to the channel. 

- [x] #3471 add client for open-discussions app to MicroMasters
  - [x] https://github.com/mitodl/open-discussions-client/issues/2 create_channel API
  - [x] https://github.com/mitodl/open-discussions-client/issues/3 subscriptions API
- [x] mitodl/open-discussions#111 add authentication and authorization to open-discussions /create_channel API
- [x] mitodl/open-discussions#112 subscribe/unsubscribe API for open-discussions
- [x] mitodl/open-discussions#113 create user API for open-discussions
- [ ] MM Create Channel front-end
  - [ ] #3473 MM Create Channel react component
  - [x] #3474 Add “create channel” button to search results page
- [x] #3475 MicroMasters create channel API
  - [ ] create percolate query
  - [ ] create channel (program staff are admins)
  - [ ] subscribe all users in query result
- [x] https://github.com/mitodl/open-discussions/issues/128 Add channel_admins API
