### ISSUE TITLE
add client for open-discussions app

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3471]
part of #3467 

The MicroMasters app will need privileged API access to the open-discussions application. 

We'll use a JWT token to authenticate and authorize the MicroMasters app to open-discussions. 

For the create a channel epic (#3467), the client will need to use the following APIs:
- [ ] mitodl/open-discussions#111 /create channel (needs authentication and authorization)
- [ ] mitodl/open-discussions#112 /subscribe (to be written)
- [x] mitodl/open-discussions#113 /create_user (if the user doesn't exist in open-discussions)

**Comment by rhysyngsun** [comment]
The client api now exists over at [mitodl/open-discussions-client](https://github.com/mitodl/open-discussions-client).

**Comment by pdpinch** [comment]
We can close this an open separate issues for the other apis

**Comment by rhysyngsun** [comment]
https://github.com/mitodl/open-discussions-client/issues/2
https://github.com/mitodl/open-discussions-client/issues/3
