### ISSUE TITLE
authenticate MM learner into discussions application

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3479]
To do this we're going to:

- [x] (PR: mitodl/open-discussions#119) Add `django-rest-framework-jwt` to OD and expose a private API to MM for getting new tokens
- [x] (PR: mitodl/micromasters#3504) MM will set an HTTPONLY cookie on a common parent subdomain.
- [ ] https://github.com/mitodl/open-discussions/issues/153 In case of an expired token on the OD side, OD will perform a background request browserside to MM to get a new token.
- [ ] https://github.com/mitodl/open-discussions/issues/153 If the MM session expired or they don't have a token (and thus we can't get a new token), a hard redirect to MM is performed to login and issue new token. User is then redirected back to OD for the page they were trying to access.
