### ISSUE TITLE
Dashboard: "Recent Posts" discussion widget

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3480]
As a learner, I would like to see the top posts from my subscribed channels on my dashboard. 

<img src="https://user-images.githubusercontent.com/430126/29299759-210a41d0-813f-11e7-83ee-096a52607abd.png" width="350">
(from https://projects.invisionapp.com/share/NB7VM1GSG#/screens/242718039_Dashboard_with_Discussions_card)

### acceptance criteria
- [x] #3476 react component for discussions widget
- [x] #3477  front-end API for discussions widget
- [x] #3478 Add /front_page API to open-discussions client
- [x] #3479 authenticate MM learner into discussions application
- [x] mitodl/open-discussions#85 Apply styles to open-discussions app

**Comment by pdpinch** [comment]
This is done. Thanks @aliceriot !
