### ISSUE TITLE
MicroMasters Program Certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#3517]
As a learner, after I pass all the course in a program, I'd like to be able to see my program certificate. 

acceptance criteria: 
- [x] #3520 Create program certificate when learner passes all courses in program
- [x] #3519 Add template for program certificates
- [x] #3492 Add overall final grade data to the dashboard API
- [x] #3521 add link on ProgressWidget to program certificate 

related issues:
- [ ] notify users on certificate creation

**Comment by pdpinch** [comment]
This is done. Thanks @annagav !
