### ISSUE TITLE
Learner Records for FA courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4097]
As a learner, when I have earned a course certificate or a program certificate, I need a way to share it with other institutions and employers. 

We'd like to implement a system similar to [edX's Learner Records](https://partners.edx.org/announcements/coming-soon-learner-records). 

### MVP acceptance criteria
- [x] #4206 learner can access a Learner record page for appropriate programs with a list of courses, grades and passing status
  - [x] #4208 record includes a "Letter Grade"
  - [x] #4212 record includes a count of attempts 
- [x] #4209 sharing the learner record generates a shareable URL 
- [x] #4213 link from dashboard to learner record
- [ ] turn it on in production

### post MVP
- [ ] #4211 send record to partner institutions 
- [ ] #4245 display last updated date on learner record
- [ ] #4210 shared record can be downloaded as a CSV

### questions
- what access controls, if any, are necessary for the learner record? Can it behave the same as the course and program certificates? 
  **A:** The learner record page itself is accessible only by the user. When a record is shared, the shared URL is generated and is not protected.

**Comment by pdpinch** [comment]
We can close this epic when student records are turned on in production.

**Comment by pdpinch** [comment]
@annagav turned this on in production, so we can close the MVP epic. There a few follow-up issues.
