### ISSUE TITLE
Electives for FA courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#4251]
In September 2019, DEDP would like to offer a new course 14.75x. The three courses 14.73x, 14.740x and 14.75x would form an elective group, with learners required to pass (at least) two of the three in order to complete the program. 

The MicroMasters team would like us to add the new 14.750x course to the dashboard by end of July 2019. MVP requires changes to program logic, but we probably won't have time to make significant changes to the UX of the learner dashboard. 

### MVP acceptance criteria
- [x] develop a data model for managing the configuration of electives (possibly some kind of set?) 
- [x] update the progress card on the learner dashboard to handle the elective properly
- [x] update the program credential creation logic to reflect the fact the the learner is required to pass only two of the three electives

### out of scope for MVP
- add a notice to the learner dashboard alerting learners to the fact that the two courses are elective (text and design TBD) 

### related issues (nice to have)
- only display courses in the learner record that the learner has attempted (diverging from edX current practice of showing all courses in the program) 

### questions
*Q:* How/does this affect program coupons?

**Comment by pdpinch** [comment]
Updated the description with new dates and definition of MVP

**Comment by pdpinch** [comment]
We can call this done.
