### ISSUE TITLE
Enrollment / profile creation

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#5]
As a learner, I want to enroll in micromasters, creating a user profile. 

When we can we will also capture data from the edX profile. Users shouldn't have to enter data twice. 

- [x] discovery on edx learner profile & api
- [x] #18 create a model
- [x] #18 create an API
- [x] #19 react container for user profile
