### ISSUE TITLE
Personalized course pricing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#534]
For a description of this epic please see https://goo.gl/OWZzva
## Stories:
- [x] #937 Personalized Pricing: add section to dashboard, when required by programs 
- [x] #988 Course price calculator
- [x] #989 Learner uploads supporting documents
- [x] #990 Staff interface for reviewing learners submitted docs
- [x] #940 Dashboard: Add tooltip with personal pricing info
## Removed stories
- ~~#991 Payment / Coupons management~~
