### ISSUE TITLE
Student dashboard MVP

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#6]
As a learner, I want to be able to view my progress in my micromasters. If I'm enrolled in multiple micromasters, I need to see all of them. I'd like to see a list of all the course in each micromasters, with an indication of which ones I've enrolled in and my current score, with an indication if its estimate or final. There should be information about when enrollment opens for ones that I haven't enrolled in yet. 

This will require interaction with several APIs:

- [X] #20 MM API to determine which micromasters I'm enrolled in 
- [x] #3 student enrollment to see which courses are enrolled
- [x] courses api (?) to find start dates
- [x] display student id #69 
- [x] display student avatar #67 
- [x] enforce login #98 

Not MVP:
- [ ] account menu #65 
- [x] logout #99
- [ ] "student progress" which probably doesn't have a public API currently 
- [ ] Analytics API to see how I compare to other students (if we decide to go that route)

**Comment by pdpinch** [comment]
Some information on grading:

https://openedx.atlassian.net/wiki/display/TNL/edX+Grading+Guide+for+Developers
