### ISSUE TITLE
Sign-up: change "where are you from" to country of birth & nationality

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#737]
We will ask users for country of birth and nationality, instead of the full country, region and city of birth. This fits better with some future use cases for this profile data. 

![image](https://cloud.githubusercontent.com/assets/430126/18098538/a505fa4e-6eb0-11e6-814b-d4351f8cd02d.png)

The text and style for the tooltip is below: 

![image](https://cloud.githubusercontent.com/assets/20047260/17441844/f3c9be2c-5b00-11e6-98f7-d938f4334820.png)

# Acceptance Criteria

- [ ] update profile model to include nationality (and remove birth_region and birth_city) (#775)
- [ ] update serialization for elastic search (#775)
- [ ] update profile API (#775); nationality is an optional field
- [ ] update react component
- [ ] use a simple country list for nationalities
- [ ] implement tool tip on click, consistent with other tool tips UX and styling

# Out of scope

- updating search results

**Comment by aliceriot** [comment]
is nationality a drop-down or a free form text box?

**Comment by aliceriot** [comment]
if it's the former, do we have a list to work with?

**Comment by aliceriot** [comment]
we might be able to use this: https://gist.github.com/didats/8154290

although we'd probably want to reformat it as JSON

**Comment by aliceriot** [comment]
@pdpinch do we have an idea of what we want to do with this yet?

**Comment by noisecapella** [comment]
Just a thought that I had this morning, but national origin is a protected category for employment. I'm not sure what the regulations are regarding admissions but I'm wondering if it sends the wrong message to ask for a person's birth country. I can't think of other forms which ask for this information. In general if we ask for pieces of information just for analytics we should communicate that explicitly, else they will assume the worst.

It also feels like we're invalidating their nationality by asking this question. If they immigrate to the US and become a citizen, they are equal to natural born citizens under the law. If we have a good reason for this question we should be explicit about expressing that.

**Comment by aliceriot** [comment]
I agree, I think in general we should be a little more explicit about how information that users provide is going to be used.

When I'm signing up for a service, if they ask me for a whole bunch of info but it's unclear what it's for (or it's unclear they're going to use it in my interest) I'll often input fake data.

**Comment by roberthouse54** [comment]
I agree with these comments. I believe the reason we are asking for nationality and Country of Birth is because there are some institutions that have expressed an interest in awarding scholarships. But I think there is only one of these, and we do not communicate to the user why we are asking for so much information. It feels pretty invasive to me.

**Comment by pdpinch** [comment]
I'll see what I can w/r/t admission polices. 

Rob, let's follow up with Erdin?

**Comment by pdpinch** [comment]
I spoke with Erdin. 

1. These fields will be optional
2. We need to alert the user to why we collect this information. @roberthouse54 can you work on a UI for this? We can also draft some copy for Erdin to review. 
3. The explanation should link to [MIT's nondiscrimination policy](http://web.mit.edu/referencepubs/nondiscrimination/)
3. The copy should be reviewed by OGC, but they have signed off on the concept of collecting this data (as MIT does for admissions applications)

**Comment by pdpinch** [comment]
@roberthouse54 can you do some design around this?

I'm thinking of something like a link/button that could say "Why do we ask for this" Clicking it displays a pop-up with copy along the lines of:

> We ask for your nationality because some program sponsors and employers offer benefits (or even scholarships) to learners with specific backgrounds.

I think we could use the same copy for explaining country of birth. 

If this makes sense, I'll run it by OGC as well.

**Comment by roberthouse54** [comment]
That sounds fine. I can do the design, but I don't want to own the copy.

**Comment by pdpinch** [comment]
@roberthouse54 can you update the designs and/or let us know how you'd like the button and the pop-up to work?

**Comment by roberthouse54** [comment]
![where_are_you_from_tooltip 2x](https://cloud.githubusercontent.com/assets/20047260/17441844/f3c9be2c-5b00-11e6-98f7-d938f4334820.png)

**Comment by pdpinch** [comment]
@noisecapella I updated the description. Let me know if you have any questions.

**Comment by pdpinch** [comment]
I updated the description to reflect that we will use country names instead of the adjectival version of the country. We think this will be easier for users to find their country. 

We should be sure the list of countries include the following (except "other"):

<img width="161" alt="screen shot 2016-09-01 at 10 40 05 am" src="https://cloud.githubusercontent.com/assets/430126/18171761/14cce000-7031-11e6-86a5-a74881410a1c.png">
