### ISSUE TITLE
Current Grades Epic

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#761]
As a learner, I would like to see my current grades in my dashboard, and be able to compare it to other learners in the same micromasters.

As a faculty and staff, I'd like to be able to see the current grades of individual learners and be able to filter search results based on grade, so I can send customized messages to learners. 

This epic covers:

- [ ] Exposing grades on edx.org via API, both writing a proposal and implementation
- [ ] Fetching the learner's current grade when they use the dashboard
- [ ] periodically refreshing the current grade of all registered learners
- [ ] Presenting the current grade for each course in the learner dashboard
- [ ] Presenting the learner's current grade in a histogram of all learner's grades on the learner dashboard
- [ ] Presenting the learner's current grade in search results in the staff search

**Comment by Ferdi** [comment]
@pdpinch @giocalitri is this up to date with the latest work that @giocalitri is doing with final grade ? If not can you update pls ?

**Comment by pdpinch** [comment]
I added a checkbox for the final grade epic, #1856
