### ISSUE TITLE
ecommerce

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#803]
As a micromasters team, I would like to offer a premium version of my course, with added features delivered through the MicroMasters portal. I would also like to offer financial aid, based on the individual situation of the applicant. I also need to be able to track the payments and progress of individual students through the portal. 

Currently edX allows two tracks, audit and verified. If we want to offer a premium track with some additional features, we can sell it through the MicroMasters portal, collecting payment, fulfilling course enrollments and fulfilling any value-added benefits. 

This epic includes the necessary commerce features to make a 3rd track feasible, namely:

- [ ] ecommerce on a program-by-program basis
- [ ] Integration with Cybersource, MIT's preferred ecommerce provider
- [ ] Integration with PayPal, a more user-friendly alternative which MIT is on the cusp of supporting
- [ ] Fulfillment through edX, meaning that, once a purchase is completed, we enroll the user in a verified track
- ~~discount pricing~~
- [ ] financial aid application, based on the College Board's fianancial aid calculator
- [ ] integration with edX's ID verification system, so we can included a verified identity in the financial aid decision (requires some more discovery)
- [ ] fulfillment of any additional features (e.g. tutoring), including restricting access by learners who have not paid
- [ ] ability of MIT faculty and ODL staff to view payment history of each learner
- [ ] data integration with MIT research systems

**Comment by pdpinch** [comment]
#closed in favor of #1058
