### ISSUE TITLE
Home Page: update template to match current design

### ISSUE THREAD

**Issue by pdpinch** [mitodl/micromasters#919]
![mm_lp 2x](https://cloud.githubusercontent.com/assets/430126/18008793/9863c4c4-6b77-11e6-968d-46dbd8c59ef8.jpg)

# acceptance criteria:

- [ ] match current design, including template & styles
- [ ] header consistent with the rest of the site (#730)
- [ ] Pull Program thumbnails, descriptions and links from program model (see also #653/#658, #573)
- [ ] fix CSS issue (#892)
- [ ] update styling of mail form to match [new design](https://cloud.githubusercontent.com/assets/430126/18179970/e612462a-7052-11e6-8c8b-e67d58abc293.png)
- [ ] fix https bug in mail form #965

# related issues:

- #944 allow updates to program thumbnails, etc. 
- #917 Sign Up / Get started modal
