### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Ferdi** [mitodl/micromasters#946]
Tentative roadmap with rough estimates.
### October 7, 2016
#1113 : Sign in / up workflow
#1111 : MM home page: Improvements
#1112 : MM program pages: Improvements
#1116 : Financial Aid: Backend/APIs
#1115 : Financial aid workflow : UI
# ....     : Financial Review page
#1114 : Dashboard: Course statuses
#1220 : Production Ready
## Dashboard
- [ ] #600 : Dashboard: Learner near me widget
- [x] #938 : Dashboard: Display course prices
- [ ] #939 : Dashboard: Display multiple runs of the same course
- [x] #940 : Dashboard: Add tool-tip with financial aid info 
## User Signup
- [x] #1183 : TOS back in sign-up form
- [x] #1105 : Sign-up: display program drop-down for users with no program
## Learner Search
- [ ] #932 : Learner search - course staff:  Add city (3rd level) to location facet 
- [ ] #933 : Learner search - course stuff: Add courses facet
- [ ] #935 : Learner search - learner: Learners should be able to search for other learners
- [ ] #943 : Learner search - learner: Learners should be able to e-mail other learners
- [ ] #996: Search: Completed courses facet

**Comment by pdpinch** [comment]
Updated description 9/30. 19/32 boxes checked, or about 60%. However, there are new issues that are missing from this list now.

**Comment by pdpinch** [comment]
This is irrelevant now.

**Comment by pdpinch** [comment]
We're not currently planning to finish everything on this roadmap.
